-- Projects table (you might already have this)
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  image TEXT,
  category TEXT,
  tech TEXT[],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Page views table
CREATE TABLE IF NOT EXISTS page_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_path TEXT NOT NULL,
  viewed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  visitor_id TEXT -- You can use this to track unique visitors (can be anonymous)
);

-- Function to get total projects
CREATE OR REPLACE FUNCTION get_total_projects()
RETURNS TABLE (
  total_count BIGINT,
  monthly_change BIGINT
) 
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    COUNT(*)::BIGINT as total_count,
    COUNT(*) FILTER (WHERE created_at >= date_trunc('month', NOW()))::BIGINT as monthly_change
  FROM projects;
END;
$$;

-- Function to get daily views
CREATE OR REPLACE FUNCTION get_daily_views()
RETURNS TABLE (
  today_count BIGINT,
  yesterday_count BIGINT
) 
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    COUNT(*) FILTER (WHERE viewed_at::date = CURRENT_DATE)::BIGINT as today_count,
    COUNT(*) FILTER (WHERE viewed_at::date = CURRENT_DATE - 1)::BIGINT as yesterday_count
  FROM page_views;
END;
$$;

-- Function to get monthly views
CREATE OR REPLACE FUNCTION get_monthly_views()
RETURNS TABLE (
  current_month_count BIGINT,
  last_month_count BIGINT
) 
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    COUNT(*) FILTER (WHERE viewed_at >= date_trunc('month', NOW()))::BIGINT as current_month_count,
    COUNT(*) FILTER (
      WHERE viewed_at >= date_trunc('month', NOW() - interval '1 month') 
      AND viewed_at < date_trunc('month', NOW())
    )::BIGINT as last_month_count
  FROM page_views;
END;
$$; 